### ISSUE TITLE
Problem with Google Maps Controls

### ISSUE THREAD

**Issue by juanbrujo** [murtaugh/HTML5-Reset#60]
```css
img,
object,
embed {max-width: 100%;}
```
causing problems with Google Maps Zoom controls.

Code: [demo @ codepen.io](http://codepen.io/juanbrujo/pen/ogdPVQ)

![screen shot 2015-02-24 at 16 57 28](https://cloud.githubusercontent.com/assets/362186/6357772/a602f09c-bc45-11e4-94a7-cebcbda1e03b.png)
